# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  - group: Terraformvariables
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
    - job: TerraformCreateResources
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'

      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          ls *
        displayName: 'Check files before terraform init'
      - task: TerraformTaskV4@4
        displayName: 'Initialize terraform'
        inputs:
          provider: 'azurerm'
          command: 'init'
          commandOptions: '-migrate-state'
          workingDirectory: '$(System.DefaultWorkingDirectory)/'
          backendServiceArm: 'terraform-databricks'
          backendAzureRmResourceGroupName: 'Terraformfiles'
          backendAzureRmStorageAccountName: 'tfstatefileslearning'
          backendAzureRmContainerName: 'terraformstatefiles'
          backendAzureRmKey: 'databricksproject.tfstate'

      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          ls *
        displayName: 'Check files after terraform init'
      - task: TerraformTaskV4@4
        displayName: 'Terraform validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/'
      #  AAD Token creation task is not required as Service Principal is already been in use.
      #  Creating the AAD Token will cause multi credentials login error.
      # - task: AzureCLI@2
      #   inputs:
      #     azureSubscription: 'terraform-databricks'
      #     scriptType: 'bash'
      #     scriptLocation: 'inlineScript'
      #     inlineScript: |
      #       aadtoken=`az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query "accessToken" -o tsv`
      #       echo "##vso[task.setvariable variable=databricks_token;]$aadtoken"
      # - script: |
      #     echo $(databricks_token)
      #   displayName: 'Print AAD token'
      
      - task: TerraformTaskV4@4
        displayName: Terraform plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/'
          commandOptions: '-var-file terraform.tfvars'
          environmentServiceNameAzureRM: 'terraform-databricks'
          
      - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          ls *
        displayName: 'Check files after terraform plan'
      
      - task: TerraformTaskV4@4
        displayName: Terraform apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/'
          commandOptions: '-auto-approve -var-file terraform.tfvars'
          environmentServiceNameAzureRM: 'terraform-databricks'
